name: Read Latest CSV on Push to Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'  # Ignore changes in README.md

jobs:
  read-csv-file:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # Prevent re-triggering

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Python Script
      run: python read_latest_csv.py
