name: Update README

on:
  push:
    branches: [main]

jobs:
  runner:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Python Script to Update README
        run: python read_latest_csv.py

      - name: Commit and Push if Changes
        run: |
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}}"
          git add README.md
          git commit -m "realized value" || exit 0  # Exit gracefully if no changes
          git push
